### ISSUE TITLE
Sparse zone network/physical depends on unavailable package

### ISSUE THREAD

**Issue by Khronos** [omniosorg/illumos-omnios#700]
Networking fails to start in a sparse zone because it depends on /network/varpd which isn't available.  Changing the network/phsycial smf to mark it optional_all allows the system to properly start up.
```
   <dependency name='network-physical-varpd' grouping='optional_all' restart_on='none' type='service'>
      <service_fmri value='svc:/network/varpd'/>
    </dependency>
```

Found in r151033

**Comment by Khronos** [comment]
Apparently this is already fixed in the next bloody release.

**Comment by citrus-it** [comment]
Hi,

Yes this was fixed in https://github.com/omniosorg/illumos-omnios/commit/74110417d5909cd45679afb8475ad5b49df01564

bloody (currently r151033) is a rolling release which does get breakage from time-to-time as things are added and tested so it's important to keep it up-to-date. Depending on what you are doing, one of the stable releases may be a better option.
